### PR TITLE
libcec version 3

### PR DESCRIPTION
**Pull request by mkreisl**
for 
- RPi1
- RPi2
- i.MX6

libcec3 also includes the required [lib]platform library as static lib. The build process provides static and shared libs for libcec3.
The libcec3 lib is already successfully tested on RPi1 and RPi2 hardware, and only build for i.MX6 (no hardware available)
All known patches are included for RPi and i.MX6, the outstanding PR (https://github.com/xbianonpi/xbian-sources-libcec/pull/1) is also included.

### CODE REVIEW

**Comment by mk01** [comment]
@mkreisl 

this must have been a huge work, specially fiddling with the patches onto new libcec3 structure, was it ?
you should have  taken already ready xbian-sources-cec with master branch where it is all combined with all patches already and rebased it into a new branch for now (and  then replace with master).

**Comment by mk01** [comment]
@mkreisl 

can you rebase the sleep() patch onto current xbiansource/master that I can merge it ?

**Comment by mkreisl** [comment]
@mk01 
I already did that - there is one open PR - thats mine ;-)

**Comment by mkreisl** [comment]
> this must have been a huge work, specially fiddling with the patches onto new libcec3 structure, was it ?
Not really, it was 'only' additional work after libcec3 was working

**Pull request merged**
